### ISSUE TITLE
Can't launch cluster after termination

### ISSUE THREAD

**Issue by samthebest** [entropyltd/spark-cloud#3]
Since terminated cluster remain in AWS for a while the following won't work if you previously had a cluster up and running:

```
        master_node = find_instance_by_name(conn, cluster_name + '-master')
```

It will grab the master instance from previous clusters, then sit in a loop for ever waiting for it to start (but it won't because it's terminated).

I found a workaround that is to manually edit the names of the instances.

Possible fixes:
1. Rename terminated instances to `name-terminated` on termination
2. Check which instances already exist and use them to generate a sequence number

**Comment by mag-** [comment]
I think renaming the instances is the way to go here, terminated instances stay in the api for ~1hour
